steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.11'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      for dir in platform/terraform/cloudbuild/*
      do 
        cd ${dir}   
        env=${dir%*/}
        env=${env#*/}
        echo ""
        echo "*************** TERRAFORM INIT ******************"
        echo "******* At environment: ${env} ********"
        echo "*************************************************"
        terraform init -reconfigure || exit 1
        cd ../../../../
      done
  timeout: '3600s'
- id: 'tf delete'
  name: 'hashicorp/terraform:1.0.11'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      for dir in platform/terraform/cloudbuild/*
      do 
        cd ${dir}   
        env=${dir%*/}
        env=${env#*/}  
        echo ""
        echo "*************** TERRAFOM PLAN ******************"
        echo "******* At environment: ${env} ********"
        echo "*************************************************"
        terraform destroy -auto-approve
        cd ../../../../
      done
  timeout: '3600s'
timeout: '3600s'