apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-agent
  namespace: voice
  labels:
    app.kubernetes.io/instance: voice-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: voice-agent
    app.kubernetes.io/version: '1.0'
    helm.sh/chart: voice-agent-100.0.1000003
    service: voice
    servicename: voice-agent
  annotations:
    meta.helm.sh/release-name: voice-agent
    meta.helm.sh/release-namespace: voice
spec:
  replicas: 1
  selector:
    matchLabels:
      servicename: voice-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: voice-agent
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: voice-agent
        app.kubernetes.io/version: '1.0'
        helm.sh/chart: voice-agent-100.0.1000003
        service: voice
        servicename: voice-agent
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service: voice-agent
        consul.hashicorp.com/connect-service-port: '11000'
        consul.hashicorp.com/connect-service-upstreams: voice-config:9100
        consul.hashicorp.com/service-tags: $POD_NAME
    spec:
      volumes:
        - name: consul-shared-secret
          secret:
            secretName: consul-voice-token
            defaultMode: 420
        - name: redis-cache-secret
          secret:
            secretName: redis-agent-token
            defaultMode: 420
        - name: redis-tenant-secret
          secret:
            secretName: redis-tenant-token
            defaultMode: 420
        - name: kafka-shared-secret
          secret:
            secretName: kafka-secrets-token
            defaultMode: 420
      containers:
        - name: voice-agent
          image: >-
            gcr.io/gts-multicloud-pe-dev/gts-multicloud-pe/voice/agent_node:100.0.1000010
          ports:
            - name: http-port
              containerPort: 11000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: voice-agent-configmap
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: REDIS_CACHE_KEY
              value: /opt/genesys/redis-secret/redis-agent-state
            - name: REDIS_TENANT_STREAM_KEY
              value: /opt/genesys/redis-tenant-secret/redis-tenant-stream
            - name: SERVICE_CONSUL_ACL_TOKEN
              value: /opt/genesys/consul-shared-secret/consul-consul-voice-token
            - name: KAFKA_SECRETS
              value: /opt/genesys/kafka-shared-secret/kafka-secrets
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: consul-shared-secret
              readOnly: true
              mountPath: /opt/genesys/consul-shared-secret
            - name: redis-cache-secret
              readOnly: true
              mountPath: /opt/genesys/redis-secret
            - name: redis-tenant-secret
              readOnly: true
              mountPath: /opt/genesys/redis-tenant-secret
            - name: kafka-shared-secret
              readOnly: true
              mountPath: /opt/genesys/kafka-shared-secret
          livenessProbe:
            httpGet:
              path: /agent_node/health
              port: 11000
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /agent_node/health
              port: 11000
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 500
            runAsGroup: 500
            runAsNonRoot: true
            readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: voice-agent
      serviceAccount: voice-agent
      securityContext: {}
      imagePullSecrets:
        - name: pullsecret
      schedulerName: default-scheduler
      dnsConfig:
        options:
          - name: ndots
            value: '3'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
