###############################################################################
#
# Find more: https://github.com/helm/charts/tree/master/stable/mssql-linux
#
###############################################################################

acceptEula:
  value: "y"

edition:
  value: "Developer"

persistence:
  enabled: true
  # existingDataClaim:
  # existingTransactionLogClaim:
  # existingBackupClaim:
  # existingMasterClaim:
  storageClass: "repd-us-west2-a-b-c"
  dataAccessMode: ReadWriteOnce
  dataSize: 200Gi
  logAccessMode: ReadWriteOnce
  logSize: 200Gi
  backupAccessMode: ReadWriteOnce
  backupLogSize: 200Gi
  masterAccessMode: ReadWriteOnce
  masterSize: 200Gi

securityContext:
  fsGroup: 10001
  runAsUser: 0

agent:
  enabled: true