apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: voice
stringData:
  CONSUL_VOICE_TOKEN: 40abd42f-b706-66c9-1ea0-8961a3402eaf
  POSTGRES_ADDR: pgdb-gws-postgresql.infra.svc.cluster.local
  POSTGRES_USER: 	postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  DNS_SERVER: 10.198.16.10
  KAFKA_ADDRESS: kafka-helm-cp-kafka.kafka.svc.cluster.local:9092
  REDIS_IP: INSERT_REDIS_IP
  REDIS_PASSWORD: INSERT_REDIS_PASSWORD
  REDIS_PORT: "6379"
  tenant_gauth_client_id: external_api_client
  tenant_gauth_client_secret: R2VuZXN5czEyMzQ=
  tenant_t100_pg_db_name: tenant_db
  tenant_t100_pg_db_password: tenant_user
  tenant_t100_pg_db_user: Genesys1234
  LOCATION: USW2